@startuml pipeline


'Two database elements side by side
database "adhd.csv" as ADHDCsv {
}
database "aspergers.csv" as AspergersCsv {
}
database "depression.csv" as DepressionCsv {
}
database "ocd.csv" as OCDCsv {
}
database "ptsd.csv" as PTSDCsv {
}

rectangle "Concatenate all CSVs into one dataframe with a new column 'subreddit'" as Concatenate

ADHDCsv -- Concatenate
AspergersCsv -- Concatenate
DepressionCsv -- Concatenate
OCDCsv -- Concatenate
PTSDCsv -- Concatenate

rectangle "remove entries with '[deleted]' or '[removed]' body" as RemoveDeleted

Concatenate -- RemoveDeleted

rectangle "Change the created_utc to creation_date" as ChangeColumn

RemoveDeleted -- ChangeColumn

rectangle "Make creation_date only date and not datetime" as RemoveTime

ChangeColumn -- RemoveTime

rectangle "Characterization of the data" as Characterization

RemoveTime -- Characterization

database "dataset.csv" as DatasetCSV {
}

database "dataset.json" as DatasetJSON {
}

Characterization -- DatasetCSV
Characterization -- DatasetJSON

@enduml